/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chat;


import chat.ChatServer;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class Chat extends javax.swing.JFrame {
    private ChatServer server;
    private ChatClient client;
    /**
     * Creates new form Czat
     */
    public Chat() {
        initComponents();
        server = new ChatServer(this);
        client = new ChatClient(this);
        
        listUzytkownicy.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) { // Dwuklik na użytkownika
                    String targetUser = listUzytkownicy.getSelectedValue();
                    if (targetUser != null) {
                        String message = JOptionPane.showInputDialog("Wpisz wiadomość do " + targetUser);
                        if (message != null && !message.trim().isEmpty()) {
                            client.sendMessage("/w " + targetUser + " " + message); // Wysyłanie wiadomości prywatnej
                        }
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCzaty = new javax.swing.JPanel();
        labelCzaty = new javax.swing.JLabel();
        labelCzatOgolny = new javax.swing.JLabel();
        separatorCzaty = new javax.swing.JSeparator();
        panelWiadomosci = new javax.swing.JPanel();
        labelWiadomosci = new javax.swing.JLabel();
        labelAktualnyCzat = new javax.swing.JLabel();
        btnWyslij = new javax.swing.JButton();
        separatorWiadomosci = new javax.swing.JSeparator();
        btnZakoncz = new javax.swing.JButton();
        labelStanSerwera = new javax.swing.JLabel();
        labelCzyUruchomiony = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaWiadomosci = new javax.swing.JTextArea();
        btnUruchomSerwer = new javax.swing.JButton();
        fieldWiadomosc = new javax.swing.JTextField();
        btnPolacz = new javax.swing.JButton();
        panelUzytkownicy = new javax.swing.JPanel();
        labelUzytkownicy = new javax.swing.JLabel();
        czatySeparator1 = new javax.swing.JSeparator();
        separatorUzytkownicy = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        listUzytkownicy = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCzaty.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelCzaty.setText("Czaty");

        labelCzatOgolny.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCzatOgolny.setText("Ogólny");

        javax.swing.GroupLayout panelCzatyLayout = new javax.swing.GroupLayout(panelCzaty);
        panelCzaty.setLayout(panelCzatyLayout);
        panelCzatyLayout.setHorizontalGroup(
            panelCzatyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCzatyLayout.createSequentialGroup()
                .addGroup(panelCzatyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCzatyLayout.createSequentialGroup()
                        .addGroup(panelCzatyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCzatyLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(labelCzatOgolny))
                            .addGroup(panelCzatyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelCzaty)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCzatyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separatorCzaty)))
                .addContainerGap())
        );
        panelCzatyLayout.setVerticalGroup(
            panelCzatyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCzatyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelCzaty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separatorCzaty, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelCzatOgolny)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        labelWiadomosci.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelWiadomosci.setText("Wiadomości");

        labelAktualnyCzat.setText("Ogólny");

        btnWyslij.setText("Wyślij");
        btnWyslij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWyslijActionPerformed(evt);
            }
        });

        btnZakoncz.setText("Zakończ");
        btnZakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZakonczActionPerformed(evt);
            }
        });

        labelStanSerwera.setText("Stan serwera:");

        labelCzyUruchomiony.setText("Wyłączony");

        areaWiadomosci.setEditable(false);
        areaWiadomosci.setColumns(20);
        areaWiadomosci.setRows(5);
        jScrollPane2.setViewportView(areaWiadomosci);

        btnUruchomSerwer.setText("Uruchom serwer");
        btnUruchomSerwer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUruchomSerwerActionPerformed(evt);
            }
        });

        btnPolacz.setText("Połącz");
        btnPolacz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolaczActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWiadomosciLayout = new javax.swing.GroupLayout(panelWiadomosci);
        panelWiadomosci.setLayout(panelWiadomosciLayout);
        panelWiadomosciLayout.setHorizontalGroup(
            panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorWiadomosci)
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWiadomosci)
                            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelAktualnyCzat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZakoncz))
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                                .addComponent(fieldWiadomosc, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnWyslij, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                                .addComponent(labelStanSerwera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCzyUruchomiony)
                                .addGap(18, 18, 18)
                                .addComponent(btnUruchomSerwer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPolacz)))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelWiadomosciLayout.setVerticalGroup(
            panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnZakoncz))
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelWiadomosci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAktualnyCzat)))
                .addGap(18, 18, 18)
                .addComponent(separatorWiadomosci, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addComponent(btnWyslij, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addComponent(fieldWiadomosc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStanSerwera)
                            .addComponent(labelCzyUruchomiony)
                            .addComponent(btnUruchomSerwer)
                            .addComponent(btnPolacz))
                        .addContainerGap())))
        );

        labelUzytkownicy.setText("Aktywni użytkownicy:");

        listUzytkownicy.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                listUzytkownicyPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(listUzytkownicy);

        javax.swing.GroupLayout panelUzytkownicyLayout = new javax.swing.GroupLayout(panelUzytkownicy);
        panelUzytkownicy.setLayout(panelUzytkownicyLayout);
        panelUzytkownicyLayout.setHorizontalGroup(
            panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorUzytkownicy)
                    .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(labelUzytkownicy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(czatySeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 112, Short.MAX_VALUE)))
        );
        panelUzytkownicyLayout.setVerticalGroup(
            panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separatorUzytkownicy, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUzytkownicy)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                    .addGap(0, 172, Short.MAX_VALUE)
                    .addComponent(czatySeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 172, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUzytkownicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCzaty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWiadomosci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelCzaty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelUzytkownicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelWiadomosci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZakonczActionPerformed
        client.disconnect();
        System.exit(0);
    }//GEN-LAST:event_btnZakonczActionPerformed

    private void btnUruchomSerwerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUruchomSerwerActionPerformed
        new ChatServer(this).startServer(2011);
    }//GEN-LAST:event_btnUruchomSerwerActionPerformed

    private void btnWyslijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWyslijActionPerformed
        String msg = fieldWiadomosc.getText().trim();
        if (!msg.isEmpty()) {
            client.sendMessage(msg);
            fieldWiadomosc.setText("");
        }
    }//GEN-LAST:event_btnWyslijActionPerformed

    private void btnPolaczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolaczActionPerformed
        String serverIp = JOptionPane.showInputDialog(this, "Podaj IP serwera:", "localhost");
    
        String username = JOptionPane.showInputDialog(this, "Podaj swoją nazwę użytkownika:");

        if (username == null || username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Musisz podać nazwę użytkownika!");
            return;
        }

        boolean connected = client.connect(serverIp, 2011, username);

        if (connected) {
            labelCzyUruchomiony.setText("Połączono jako " + username);
            addMessage("[Połączono z serwerem " + serverIp + "]");
        } else {
            labelCzyUruchomiony.setText("Nie udało się połączyć");
        }
    }//GEN-LAST:event_btnPolaczActionPerformed

    private void listUzytkownicyPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_listUzytkownicyPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_listUzytkownicyPropertyChange

    private void connectToServer() {
        String ip = JOptionPane.showInputDialog(this, "Podaj IP serwera:");
        String login = JOptionPane.showInputDialog(this, "Podaj swój login:");
        if (client.connect(ip, 2011, login)) {
            labelCzyUruchomiony.setText("Połączony jako " + login);
        }
    }

    private void sendMessage() {
        String msg = fieldWiadomosc.getText().trim();
        if (!msg.isEmpty()) {
            client.sendMessage(msg);
            fieldWiadomosc.setText("");
        }
    }

    public void addMessage(String msg) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            areaWiadomosci.append(msg + "\n");
        });
    }

    public void updateUserList(String[] users) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            listUzytkownicy.setListData(users);
        });
    }

    public void updateServerStatus(String status) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            labelCzyUruchomiony.setText(status);
        });
    }

    public void addUser(String username) {
        addMessage("[Dołączył] " + username);
    }

    public void removeUser(String username) {
        addMessage("[Opuścił czat] " + username);
    }

    private void sendPrivateMessage(String targetUser) {
        String message = JOptionPane.showInputDialog(this, "Wpisz wiadomość do " + targetUser);
        if (message != null && !message.trim().isEmpty()) {
            client.sendMessage("/w " + targetUser + " " + message); // Wysyłamy wiadomość prywatną do serwera
        }
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new Chat().setVisible(true));
    }
    
    /**
     * @param args the command line arguments
     */           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaWiadomosci;
    private javax.swing.JButton btnPolacz;
    private javax.swing.JButton btnUruchomSerwer;
    private javax.swing.JButton btnWyslij;
    private javax.swing.JButton btnZakoncz;
    private javax.swing.JSeparator czatySeparator1;
    private javax.swing.JTextField fieldWiadomosc;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAktualnyCzat;
    private javax.swing.JLabel labelCzatOgolny;
    private javax.swing.JLabel labelCzaty;
    private javax.swing.JLabel labelCzyUruchomiony;
    private javax.swing.JLabel labelStanSerwera;
    private javax.swing.JLabel labelUzytkownicy;
    private javax.swing.JLabel labelWiadomosci;
    private javax.swing.JList<String> listUzytkownicy;
    private javax.swing.JPanel panelCzaty;
    private javax.swing.JPanel panelUzytkownicy;
    private javax.swing.JPanel panelWiadomosci;
    private javax.swing.JSeparator separatorCzaty;
    private javax.swing.JSeparator separatorUzytkownicy;
    private javax.swing.JSeparator separatorWiadomosci;
    // End of variables declaration//GEN-END:variables
}
