/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prawieword;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import javax.swing.JColorChooser;

/**
 *
 * @author Admin
 */
public class PrawieWordJFrame extends javax.swing.JFrame {
    
    Graphics2D grafika;
    String wybranaCzcionka = "Arial";
    int pogrubienieKursywa = 0;
    int wielkoscCzcionki = 11;
    Color kolorCzcionki = Color.BLACK;
    Color kolorTla = Color.WHITE;
    String tekst;
    
    /**
     * Creates new form PrawieWordJFrame
     */
    public PrawieWordJFrame() {
        initComponents();
        
        mainTextArea.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        czcionkaKombi = new javax.swing.JComboBox<>();
        wielkoscCzcionkiKombi = new javax.swing.JComboBox<>();
        pogrubienieToggle = new javax.swing.JToggleButton();
        kursywaToggle = new javax.swing.JToggleButton();
        kolorCzcionkiLabel = new javax.swing.JLabel();
        kolorCzcionkiField = new javax.swing.JTextField();
        kolorTlaLabel = new javax.swing.JLabel();
        kolorTlaField = new javax.swing.JTextField();
        zawijanieTekstuCheck = new javax.swing.JCheckBox();
        wklejButton = new javax.swing.JButton();
        wytnijButton = new javax.swing.JButton();
        kopiujButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        plikMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        czcionkaKombi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Times New Roman", "Courier New", "Verdana", "Tahoma", "Lucida Console", "Monospaced", "Dialog", "SansSerif", "Serif" }));
        czcionkaKombi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czcionkaKombiActionPerformed(evt);
            }
        });

        wielkoscCzcionkiKombi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3", "5", "7", "9", "11", "13", "15", "17", "19", "21", "23", "25", "27", "29", "31" }));
        wielkoscCzcionkiKombi.setSelectedIndex(5);
        wielkoscCzcionkiKombi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wielkoscCzcionkiKombiActionPerformed(evt);
            }
        });

        pogrubienieToggle.setText("B");
        pogrubienieToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogrubienieToggleActionPerformed(evt);
            }
        });

        kursywaToggle.setText("I");
        kursywaToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursywaToggleActionPerformed(evt);
            }
        });

        kolorCzcionkiLabel.setText("Kolor czcionki:");

        kolorCzcionkiField.setEditable(false);
        kolorCzcionkiField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kolorCzcionkiFieldMouseClicked(evt);
            }
        });

        kolorTlaLabel.setText("Kolor tła:");

        kolorTlaField.setEditable(false);
        kolorTlaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kolorTlaFieldMouseClicked(evt);
            }
        });

        zawijanieTekstuCheck.setSelected(true);
        zawijanieTekstuCheck.setText("Zawijaj tekst");
        zawijanieTekstuCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zawijanieTekstuCheckActionPerformed(evt);
            }
        });

        wklejButton.setText("Wklej");
        wklejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wklejButtonActionPerformed(evt);
            }
        });

        wytnijButton.setText("Wytnij");
        wytnijButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wytnijButtonActionPerformed(evt);
            }
        });

        kopiujButton.setText("Kopiuj");
        kopiujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kopiujButtonActionPerformed(evt);
            }
        });

        mainTextArea.setColumns(20);
        mainTextArea.setRows(5);
        mainTextArea.setText("Przykładowy tekst");
        jScrollPane1.setViewportView(mainTextArea);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(czcionkaKombi, 0, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wielkoscCzcionkiKombi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pogrubienieToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kursywaToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kolorCzcionkiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kolorCzcionkiField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kolorTlaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kolorTlaField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(zawijanieTekstuCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(kopiujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wytnijButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wklejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pogrubienieToggle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(czcionkaKombi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wielkoscCzcionkiKombi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kursywaToggle)
                        .addComponent(kolorCzcionkiLabel)
                        .addComponent(kolorCzcionkiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kolorTlaLabel)
                        .addComponent(kolorTlaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zawijanieTekstuCheck)
                        .addComponent(wklejButton)
                        .addComponent(wytnijButton)
                        .addComponent(kopiujButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        plikMenu.setText("Plik");
        jMenuBar1.add(plikMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kursywaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursywaToggleActionPerformed
        if (pogrubienieKursywa == 0) {
            pogrubienieKursywa = 2;
        } else if (pogrubienieKursywa == 2) {
            pogrubienieKursywa = 0;
        } else if (pogrubienieKursywa == 1) {
            pogrubienieKursywa = 3;
        } else if (pogrubienieKursywa == 3) {
            pogrubienieKursywa = 1;
        }
        
        Font czcionka = new Font(wybranaCzcionka, pogrubienieKursywa, wielkoscCzcionki);
        mainTextArea.setFont(czcionka);
    }//GEN-LAST:event_kursywaToggleActionPerformed

    private void zawijanieTekstuCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zawijanieTekstuCheckActionPerformed
        if (!zawijanieTekstuCheck.isSelected()) {
            mainTextArea.setLineWrap(false);
        } else {
            mainTextArea.setLineWrap(true);
        }
    }//GEN-LAST:event_zawijanieTekstuCheckActionPerformed

    private void pogrubienieToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogrubienieToggleActionPerformed
        if (pogrubienieKursywa == 0) {
            pogrubienieKursywa = 1;
        } else if (pogrubienieKursywa == 1) {
            pogrubienieKursywa = 0;
        } else if (pogrubienieKursywa == 2) {
            pogrubienieKursywa = 3;
        } else if (pogrubienieKursywa == 3) {
            pogrubienieKursywa = 2;
        }
        
        Font czcionka = new Font(wybranaCzcionka, pogrubienieKursywa, wielkoscCzcionki);
        mainTextArea.setFont(czcionka);
    }//GEN-LAST:event_pogrubienieToggleActionPerformed

    private void wielkoscCzcionkiKombiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wielkoscCzcionkiKombiActionPerformed
        wielkoscCzcionki = wielkoscCzcionkiKombi.getSelectedIndex() * 2 + 1;
        Font czcionka = new Font(wybranaCzcionka, pogrubienieKursywa, wielkoscCzcionki);
        mainTextArea.setFont(czcionka);
    }//GEN-LAST:event_wielkoscCzcionkiKombiActionPerformed

    private void czcionkaKombiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czcionkaKombiActionPerformed
        wybranaCzcionka = czcionkaKombi.getSelectedItem().toString();
        Font czcionka = new Font(wybranaCzcionka, pogrubienieKursywa, wielkoscCzcionki);
        mainTextArea.setFont(czcionka);
    }//GEN-LAST:event_czcionkaKombiActionPerformed

    private void kolorCzcionkiFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kolorCzcionkiFieldMouseClicked
        kolorCzcionki = JColorChooser.showDialog(null, "Wybierz kolor", kolorCzcionki);
        kolorCzcionkiField.setBackground(kolorCzcionki);
        mainTextArea.setForeground(kolorCzcionki);
    }//GEN-LAST:event_kolorCzcionkiFieldMouseClicked

    private void kolorTlaFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kolorTlaFieldMouseClicked
        kolorTla = JColorChooser.showDialog(null, "Wybierz kolor", kolorTla);
        kolorTlaField.setBackground(kolorTla);
        mainTextArea.setBackground(kolorTla);
    }//GEN-LAST:event_kolorTlaFieldMouseClicked

    private void kopiujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kopiujButtonActionPerformed
        mainTextArea.copy();
    }//GEN-LAST:event_kopiujButtonActionPerformed

    private void wytnijButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wytnijButtonActionPerformed
        mainTextArea.cut();
    }//GEN-LAST:event_wytnijButtonActionPerformed

    private void wklejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wklejButtonActionPerformed
        mainTextArea.paste();
    }//GEN-LAST:event_wklejButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrawieWordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrawieWordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrawieWordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrawieWordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrawieWordJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> czcionkaKombi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kolorCzcionkiField;
    private javax.swing.JLabel kolorCzcionkiLabel;
    private javax.swing.JTextField kolorTlaField;
    private javax.swing.JLabel kolorTlaLabel;
    private javax.swing.JButton kopiujButton;
    private javax.swing.JToggleButton kursywaToggle;
    private javax.swing.JTextArea mainTextArea;
    private javax.swing.JMenu plikMenu;
    private javax.swing.JToggleButton pogrubienieToggle;
    private javax.swing.JComboBox<String> wielkoscCzcionkiKombi;
    private javax.swing.JButton wklejButton;
    private javax.swing.JButton wytnijButton;
    private javax.swing.JCheckBox zawijanieTekstuCheck;
    // End of variables declaration//GEN-END:variables
}
