/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package czat;

/**
 *
 * @author Admin
 */
public class Czat extends javax.swing.JFrame {

    /**
     * Creates new form Czat
     */
    public Czat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        czatyPanel = new javax.swing.JPanel();
        czatyLabel = new javax.swing.JLabel();
        czatOgolnyLabel = new javax.swing.JLabel();
        czatySeparator = new javax.swing.JSeparator();
        wiadomoscPanel = new javax.swing.JPanel();
        wiadomosciLabel = new javax.swing.JLabel();
        aktualnyCzatLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wiadomoscArea = new javax.swing.JTextArea();
        wyslijButton = new javax.swing.JButton();
        wiadomosciSeparator = new javax.swing.JSeparator();
        zakonczButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        czatyLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        czatyLabel.setText("Czaty");

        czatOgolnyLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        czatOgolnyLabel.setText("Ogólny");

        javax.swing.GroupLayout czatyPanelLayout = new javax.swing.GroupLayout(czatyPanel);
        czatyPanel.setLayout(czatyPanelLayout);
        czatyPanelLayout.setHorizontalGroup(
            czatyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(czatyPanelLayout.createSequentialGroup()
                .addGroup(czatyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(czatyPanelLayout.createSequentialGroup()
                        .addGroup(czatyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(czatyPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(czatOgolnyLabel))
                            .addGroup(czatyPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(czatyLabel)))
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(czatyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(czatySeparator)))
                .addContainerGap())
        );
        czatyPanelLayout.setVerticalGroup(
            czatyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(czatyPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(czatyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(czatySeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(czatOgolnyLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wiadomosciLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        wiadomosciLabel.setText("Wiadomości");

        aktualnyCzatLabel.setText("*aktualny czat*");

        wiadomoscArea.setColumns(20);
        wiadomoscArea.setLineWrap(true);
        wiadomoscArea.setRows(5);
        jScrollPane1.setViewportView(wiadomoscArea);

        wyslijButton.setText("Wyślij");

        zakonczButton.setText("Zakończ");
        zakonczButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zakonczButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wiadomoscPanelLayout = new javax.swing.GroupLayout(wiadomoscPanel);
        wiadomoscPanel.setLayout(wiadomoscPanelLayout);
        wiadomoscPanelLayout.setHorizontalGroup(
            wiadomoscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wiadomoscPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wiadomoscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wiadomosciSeparator)
                    .addGroup(wiadomoscPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wyslijButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(wiadomoscPanelLayout.createSequentialGroup()
                        .addGroup(wiadomoscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wiadomosciLabel)
                            .addGroup(wiadomoscPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(aktualnyCzatLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zakonczButton)))
                .addContainerGap())
        );
        wiadomoscPanelLayout.setVerticalGroup(
            wiadomoscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wiadomoscPanelLayout.createSequentialGroup()
                .addGroup(wiadomoscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wiadomoscPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(zakonczButton))
                    .addGroup(wiadomoscPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wiadomosciLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aktualnyCzatLabel)))
                .addGap(12, 12, 12)
                .addComponent(wiadomosciSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addGroup(wiadomoscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wiadomoscPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wiadomoscPanelLayout.createSequentialGroup()
                        .addComponent(wyslijButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(czatyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wiadomoscPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(czatyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(wiadomoscPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zakonczButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zakonczButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_zakonczButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Czat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Czat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Czat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Czat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Czat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aktualnyCzatLabel;
    private javax.swing.JLabel czatOgolnyLabel;
    private javax.swing.JLabel czatyLabel;
    private javax.swing.JPanel czatyPanel;
    private javax.swing.JSeparator czatySeparator;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea wiadomoscArea;
    private javax.swing.JPanel wiadomoscPanel;
    private javax.swing.JLabel wiadomosciLabel;
    private javax.swing.JSeparator wiadomosciSeparator;
    private javax.swing.JButton wyslijButton;
    private javax.swing.JButton zakonczButton;
    // End of variables declaration//GEN-END:variables
}
