/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package czat;

/**
 *
 * @author Admin
 */
public class Czat extends javax.swing.JFrame {

    /**
     * Creates new form Czat
     */
    public Czat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCzaty = new javax.swing.JPanel();
        labelCzaty = new javax.swing.JLabel();
        labelCzatOgolny = new javax.swing.JLabel();
        separatorCzaty = new javax.swing.JSeparator();
        panelWiadomosci = new javax.swing.JPanel();
        labelWiadomosci = new javax.swing.JLabel();
        labelAktualnyCzat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaWyslijWiadomosc = new javax.swing.JTextArea();
        btnWyslij = new javax.swing.JButton();
        separatorWiadomosci = new javax.swing.JSeparator();
        btnZakoncz = new javax.swing.JButton();
        labelStanSerwera = new javax.swing.JLabel();
        labelCzyUruchomiony = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaWiadomosci = new javax.swing.JTextArea();
        panelUzytkownicy = new javax.swing.JPanel();
        labelUzytkownicy = new javax.swing.JLabel();
        czatySeparator1 = new javax.swing.JSeparator();
        separatorUzytkownicy = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCzaty.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelCzaty.setText("Czaty");

        labelCzatOgolny.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCzatOgolny.setText("Ogólny");

        javax.swing.GroupLayout panelCzatyLayout = new javax.swing.GroupLayout(panelCzaty);
        panelCzaty.setLayout(panelCzatyLayout);
        panelCzatyLayout.setHorizontalGroup(
            panelCzatyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCzatyLayout.createSequentialGroup()
                .addGroup(panelCzatyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCzatyLayout.createSequentialGroup()
                        .addGroup(panelCzatyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCzatyLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(labelCzatOgolny))
                            .addGroup(panelCzatyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelCzaty)))
                        .addGap(0, 121, Short.MAX_VALUE))
                    .addGroup(panelCzatyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separatorCzaty)))
                .addContainerGap())
        );
        panelCzatyLayout.setVerticalGroup(
            panelCzatyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCzatyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelCzaty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separatorCzaty, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelCzatOgolny)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        labelWiadomosci.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelWiadomosci.setText("Wiadomości");

        labelAktualnyCzat.setText("*aktualny czat*");

        areaWyslijWiadomosc.setColumns(20);
        areaWyslijWiadomosc.setLineWrap(true);
        areaWyslijWiadomosc.setRows(5);
        jScrollPane1.setViewportView(areaWyslijWiadomosc);

        btnWyslij.setText("Wyślij");

        btnZakoncz.setText("Zakończ");
        btnZakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZakonczActionPerformed(evt);
            }
        });

        labelStanSerwera.setText("Stan serwera:");

        labelCzyUruchomiony.setText("Wyłączony");

        areaWiadomosci.setColumns(20);
        areaWiadomosci.setRows(5);
        jScrollPane2.setViewportView(areaWiadomosci);

        javax.swing.GroupLayout panelWiadomosciLayout = new javax.swing.GroupLayout(panelWiadomosci);
        panelWiadomosci.setLayout(panelWiadomosciLayout);
        panelWiadomosciLayout.setHorizontalGroup(
            panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorWiadomosci)
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWiadomosci)
                            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelAktualnyCzat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZakoncz))
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnWyslij, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                                .addComponent(labelStanSerwera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCzyUruchomiony)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelWiadomosciLayout.setVerticalGroup(
            panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWiadomosciLayout.createSequentialGroup()
                .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnZakoncz))
                    .addGroup(panelWiadomosciLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelWiadomosci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAktualnyCzat)))
                .addGap(12, 12, 12)
                .addComponent(separatorWiadomosci, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWiadomosciLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelWiadomosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStanSerwera)
                            .addComponent(labelCzyUruchomiony))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWiadomosciLayout.createSequentialGroup()
                        .addComponent(btnWyslij, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        labelUzytkownicy.setText("Aktywni użytkownicy:");

        javax.swing.GroupLayout panelUzytkownicyLayout = new javax.swing.GroupLayout(panelUzytkownicy);
        panelUzytkownicy.setLayout(panelUzytkownicyLayout);
        panelUzytkownicyLayout.setHorizontalGroup(
            panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUzytkownicyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separatorUzytkownicy, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelUzytkownicy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(czatySeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelUzytkownicyLayout.setVerticalGroup(
            panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separatorUzytkownicy, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUzytkownicy)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(panelUzytkownicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUzytkownicyLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(czatySeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCzaty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUzytkownicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWiadomosci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWiadomosci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCzaty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUzytkownicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZakonczActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnZakonczActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Czat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Czat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Czat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Czat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Czat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaWiadomosci;
    private javax.swing.JTextArea areaWyslijWiadomosc;
    private javax.swing.JButton btnWyslij;
    private javax.swing.JButton btnZakoncz;
    private javax.swing.JSeparator czatySeparator1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAktualnyCzat;
    private javax.swing.JLabel labelCzatOgolny;
    private javax.swing.JLabel labelCzaty;
    private javax.swing.JLabel labelCzyUruchomiony;
    private javax.swing.JLabel labelStanSerwera;
    private javax.swing.JLabel labelUzytkownicy;
    private javax.swing.JLabel labelWiadomosci;
    private javax.swing.JPanel panelCzaty;
    private javax.swing.JPanel panelUzytkownicy;
    private javax.swing.JPanel panelWiadomosci;
    private javax.swing.JSeparator separatorCzaty;
    private javax.swing.JSeparator separatorUzytkownicy;
    private javax.swing.JSeparator separatorWiadomosci;
    // End of variables declaration//GEN-END:variables
}
