/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apka_do_malowania;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.util.ArrayList;
import javax.swing.JColorChooser;

/**
 *
 * @author Admin
 */
public class apka extends javax.swing.JFrame {

    Color brushColor = Color.BLACK;
    int old_mouse_x = 0;
    int old_mouse_y = 0;
    Graphics2D graphics2D;
    boolean draw_figure = false;
    int first_mouse_x = 0;
    int first_mouse_y = 0;
    int old_width = 0;
    int old_height = 0;
    int lpx[] = {};
    int lpy[] = {};
    int px;
    int py;
    int i = 0;
    int ppx;
    int ppy;
    
    /**
     * Creates new form apka
     */
    public apka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        wyczysc = new javax.swing.JButton();
        kolor = new javax.swing.JButton();
        wybrany_kolor = new javax.swing.JTextField();
        grubosc_linii = new javax.swing.JComboBox<>();
        narzedzie = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 72));

        wyczysc.setText("Wyczyść");
        wyczysc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wyczyscMouseClicked(evt);
            }
        });
        wyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyczyscActionPerformed(evt);
            }
        });

        kolor.setText("Kolor");
        kolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolorActionPerformed(evt);
            }
        });

        wybrany_kolor.setEditable(false);
        wybrany_kolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wybrany_kolorActionPerformed(evt);
            }
        });

        grubosc_linii.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1px", "2px", "3px", "4px", "5px" }));

        narzedzie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ołówek", "Prostokąt", "Linia", "Okrąg", "Wielokąt" }));
        narzedzie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narzedzieActionPerformed(evt);
            }
        });

        jLabel2.setText("Grubość linii");

        jLabel1.setText("Narzędzie");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(narzedzie, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(grubosc_linii, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wybrany_kolor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addComponent(wyczysc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(narzedzie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grubosc_linii, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wyczysc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wybrany_kolor))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolorActionPerformed
        brushColor = JColorChooser.showDialog(null, "Wybierz kolor", brushColor);
        wybrany_kolor.setBackground(brushColor);
    }//GEN-LAST:event_kolorActionPerformed

    private void wybrany_kolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wybrany_kolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wybrany_kolorActionPerformed

    private void narzedzieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narzedzieActionPerformed
        
    }//GEN-LAST:event_narzedzieActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        old_mouse_x = evt.getX();
        old_mouse_y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       if (narzedzie.getSelectedIndex() == 0) {
           graphics2D = (Graphics2D)jPanel1.getGraphics();
           if (graphics2D != null) {
               graphics2D.setColor(brushColor);
               graphics2D.setStroke(new BasicStroke(grubosc_linii.getSelectedIndex()+1));
               graphics2D.drawLine(old_mouse_x, old_mouse_y, evt.getX(), evt.getY());
           }
           old_mouse_x = evt.getX();
           old_mouse_y = evt.getY();
       }
    }//GEN-LAST:event_jPanel1MouseDragged

    private void wyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyczyscActionPerformed
        
    }//GEN-LAST:event_wyczyscActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if (narzedzie.getSelectedIndex() > 0 && narzedzie.getSelectedIndex() < 4 && draw_figure == false) {
            draw_figure = true;
            first_mouse_x = old_mouse_x;
            first_mouse_y = old_mouse_y;
            old_width = 0;
            old_height = 0;
        } else if (narzedzie.getSelectedIndex() > 0 && narzedzie.getSelectedIndex() < 4 && draw_figure == true) {
            draw_figure = false;
        } else if (narzedzie.getSelectedIndex() == 4 && draw_figure == false) {
            draw_figure = true;
            first_mouse_x = old_mouse_x;
            first_mouse_y = old_mouse_y;
            old_width = 0;
            old_height = 0;
            lpx = new int[100];
            lpy = new int[100];
            
            if (i == 0) {
                ppx = evt.getX();
                ppy = evt.getY();
                lpx[0] = ppx;
                lpy[0] = ppy;
                i = 1;
            }
            
            graphics2D = (Graphics2D)jPanel1.getGraphics();
            graphics2D.setColor(brushColor);
            graphics2D.fillOval(ppx, ppy, 5, 5);
        } else if (narzedzie.getSelectedIndex() == 4 && draw_figure == true) {            
            px = evt.getX();
            py = evt.getY();
            lpx[i] = px;
            lpy[i] = py;
            i += 1;

            graphics2D = (Graphics2D)jPanel1.getGraphics();
            graphics2D.setColor(brushColor);
            graphics2D.fillOval(px, py, 5, 5);
            
            if (i > 2 && Math.abs(px - ppx) < 10 && Math.abs(py - ppy) < 10) {
                int lpxf[];
                lpxf = new int[i+1];
                int lpyf[];
                lpyf = new int[i+1];
                for (int z = 0; z <= i; z++) {
                    lpxf[z] = lpx[z];
                    lpyf[z] = lpy[z];
                }
                
                Polygon polygon = new Polygon(lpxf, lpyf, i);
                graphics2D.setColor(brushColor);
                graphics2D.fill(polygon);
                
                i = 0;
                draw_figure = false; 
            }
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        if (draw_figure == true) {
            int a;
            int b;
            if (first_mouse_x < evt.getX()) {
                a = first_mouse_x;
            } else {
                a = evt.getX();
            }
            if (first_mouse_y < evt.getY()) {
                b = first_mouse_y;
            } else {
                b = evt.getY();
            }
            
            int width = evt.getX() - a;
            int height = evt.getY() - b;
            
            graphics2D = (Graphics2D)jPanel1.getGraphics();
            
            if (narzedzie.getSelectedIndex() == 1) {
                graphics2D.setColor(Color.WHITE);
                graphics2D.fillRect(first_mouse_x, first_mouse_y, old_width, old_height);
                graphics2D.setColor(brushColor);
                graphics2D.fillRect(first_mouse_x, first_mouse_y, width, height);
            }
            
            if (narzedzie.getSelectedIndex() == 2) {
                graphics2D.setColor(Color.WHITE);
                graphics2D.drawLine(first_mouse_x, first_mouse_y, old_mouse_x, old_mouse_y);
                graphics2D.setColor(brushColor);
                graphics2D.drawLine(first_mouse_x, first_mouse_y, evt.getX(), evt.getY());
            }
            
            if (narzedzie.getSelectedIndex() == 3) {
                graphics2D.setColor(Color.WHITE);
                graphics2D.fillOval(first_mouse_x, first_mouse_y, old_width, old_height);
                graphics2D.setColor(brushColor);
                graphics2D.fillOval(first_mouse_x, first_mouse_y, width, height);
            }
            
            if (narzedzie.getSelectedIndex() == 4) {
                //graphics2D.setColor(Color.WHITE);
                //graphics2D.drawLine(first_mouse_x, first_mouse_y, old_mouse_x, old_mouse_y);
                //graphics2D.setColor(brushColor);
                //graphics2D.drawLine(first_mouse_x, first_mouse_y, evt.getX(), evt.getY());
            }
            
            old_mouse_x = evt.getX();
            old_mouse_y = evt.getY();
            old_width = width;
            old_height = height;
        }
    }//GEN-LAST:event_jPanel1MouseMoved

    private void wyczyscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wyczyscMouseClicked
        graphics2D = (Graphics2D)jPanel1.getGraphics();
        graphics2D.setColor(Color.WHITE);
        graphics2D.fillRect(0, 0, 10000, 10000);
    }//GEN-LAST:event_wyczyscMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> grubosc_linii;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kolor;
    private javax.swing.JComboBox<String> narzedzie;
    private javax.swing.JTextField wybrany_kolor;
    private javax.swing.JButton wyczysc;
    // End of variables declaration//GEN-END:variables
}
